# TODO :
# El secreto en secret manager debe ser guardado como json ex. { LicenseKey: 'value' }
service: new-relic-lambda-apm

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 10
  versionFunctions: false

plugins:
  - serverless-iam-roles-per-function

package:
  patterns:
    - '!**'
    - handler.js

functions:
  newrelicapm:
    handler: newrelic-lambda-wrapper.handler
    name: newrelic-apm-ema-${sls:stage}
    description: lambda new relic apm
    memorySize: 256
    timeout: 10
    provisionedConcurrency: 1
    environment:
      NEW_RELIC_LAMBDA_HANDLER: handler.hello
      NEW_RELIC_LICENSE_KEY_SECRET: /pathto/secret/NEW_RELIC_LICENSE_KEY
    layers:
      - arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS12X:42
    iamRoleStatements:
      - Effect: Allow
        Resource: "arn:aws:secretsmanager:us-east-1:<<<<<<ACCOUNT_ID_HERE>>>>>>>>:secret:/pathto/secret/NEW_RELIC_LICENSE_KEY-randomhash"
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret